/***
    1. Clean workspace
    2. clone project
    3. configuration
    4. build image
    5. push to docker hub
    6. control ansible to run  kubernetes
***/
pipeline {
    agent any

    stages {
        stage('Clean workspace') {
            steps{
                cleanWs();
            }
        }
        stage('Clone project') {
            steps{
                git branch: 'main', credentialsId: 'gitlab-id', url: 'https://gitlab.com/huorgroup/khcomic/kh-comic-api.git'
            }   
        }
        stage('Configuration') {
            steps{
                withCredentials([usernamePassword(credentialsId: 'gitlab-id', passwordVariable: 'SECRET', usernameVariable: 'USER')]) {
                    sh'echo ${USER}'
                    sh'git clone https://${USER}:$SECRET@gitlab.com/huorgroup/khcomic/khcomic-production-env.git env'
                    sh'cp env/.env ./'
                }
            }   
        }
        stage('Build images') {
            steps{
                script {
                     withCredentials([usernamePassword(credentialsId: 'docker-hub-id', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                        sh'docker login -u ${USER} -p $PASS'
                        sh '''
                            sudo docker rmi -f ${USER}/api-comic-gateway:latest
                            sudo docker rmi -f ${USER}/api-comic-auth:latest
                            sudo docker rmi -f ${USER}/api-comic-book:latest
                            sudo docker rmi -f ${USER}/api-comic-transaction:latest
                            sudo docker build -t ${USER}/api-comic-gateway:latest -f Dockerfile.api .
                            sudo docker build -t ${USER}/api-comic-auth:latest -f Dockerfile.auth .
                            sudo docker build -t ${USER}/api-comic-book:latest -f Dockerfile.book .
                            sudo docker build -t ${USER}/api-comic-transaction:latest -f Dockerfile.transaction .
                            sudo docker push ${USER}/api-comic-gateway:latest
                            sudo docker push ${USER}/api-comic-auth:latest
                            sudo docker push ${USER}/api-comic-book:latest
                            sudo docker push ${USER}/api-comic-transaction:latest
                        '''
                    }
                }
            }   
        }
    }
}