apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-comic-rabbitmq-deveployment
  labels:
    app: api-comic-rabbitmq-label
spec:
  replicas: 1 # Number of desired replicas
  selector:
    matchLabels:
      app: api-comic-rabbitmq-label
  template:
    metadata:
      labels:
        app: api-comic-rabbitmq-label
    spec:
      restartPolicy: Always
      containers:
        - name: api-comic-rabbitmq-container
          image: rabbitmq:management # Image to be used for the container
          env:
          - name: RABBITMQ_DEFAULT_USER
            value: "guest"
          - name: RABBITMQ_DEFAULT_PASS
            value: "guest"
          ports:
          - containerPort: 5672
          - containerPort: 15672