apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: default  # Namespace where the deployment will be created
  labels:
    app: my-app
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: my-image:latest  # Image to be used for the container
          ports:
            - containerPort: 80  # Port that the container exposes
          env:  # Environment variables for the container
            - name: ENV_VAR_NAME
              value: "value"
