apiVersion: v1
kind: Service
metadata:
  name: api-comic-service
  labels:
    app: api-comic-app
spec:
  selector:
    app: api-comic-gateway-label
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer #NodePort|LoadBalancer|ExternalName
